version: '3.8'

services:
  gogemini:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GOGEMINI_PORT=${GOGEMINI_PORT}
    ports:
      - "${GOGEMINI_PORT}:${GOGEMINI_PORT}"
    depends_on:
      - db
    environment:
      - GOGEMINI_DATABASE_DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - GOGEMINI_DATABASE_TYPE=postgres
      - GOGEMINI_PORT=${GOGEMINI_PORT}
      - GOGEMINI_ADMIN_PASSWORD=${GOGEMINI_ADMIN_PASSWORD}
      - GOGEMINI_DEBUG=${GOGEMINI_DEBUG}
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: